// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtI76zLQrIy3SAljbjUCqCG-odSUmo6c',
    appId: '1:705966775275:web:42dde198aefc1f041297ae',
    messagingSenderId: '705966775275',
    projectId: 'lista-5df62',
    authDomain: 'lista-5df62.firebaseapp.com',
    storageBucket: 'lista-5df62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfACf7xuZ_GNY1uxF_V236UnACShRRYQw',
    appId: '1:705966775275:android:91cea8f04b7772331297ae',
    messagingSenderId: '705966775275',
    projectId: 'lista-5df62',
    storageBucket: 'lista-5df62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxJAiFOIkXQqMFnDBe_2-LnPLP5wkYtA',
    appId: '1:705966775275:ios:a5908a34579882a71297ae',
    messagingSenderId: '705966775275',
    projectId: 'lista-5df62',
    storageBucket: 'lista-5df62.appspot.com',
    iosClientId: '705966775275-baivh8q5chd4jj42of3e590b7oael8tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app06TaskList',
  );
}
